// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package snowflakeconnector.proxies;

public class ConnectionBuilder
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject connectionBuilderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SnowflakeConnector.ConnectionBuilder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		JdbcUrl("JdbcUrl"),
		AccountName("AccountName"),
		User("User"),
		Password("Password"),
		Db("Db"),
		Schema("Schema"),
		Role("Role"),
		Warehouse("Warehouse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConnectionBuilder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConnectionBuilder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject connectionBuilderMendixObject)
	{
		if (connectionBuilderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, connectionBuilderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.connectionBuilderMendixObject = connectionBuilderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ConnectionBuilder.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static snowflakeconnector.proxies.ConnectionBuilder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return snowflakeconnector.proxies.ConnectionBuilder.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static snowflakeconnector.proxies.ConnectionBuilder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new snowflakeconnector.proxies.ConnectionBuilder(context, mendixObject);
	}

	public static snowflakeconnector.proxies.ConnectionBuilder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return snowflakeconnector.proxies.ConnectionBuilder.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of JdbcUrl
	 */
	public final java.lang.String getJdbcUrl()
	{
		return getJdbcUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of JdbcUrl
	 */
	public final java.lang.String getJdbcUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JdbcUrl.toString());
	}

	/**
	 * Set value of JdbcUrl
	 * @param jdbcurl
	 */
	public final void setJdbcUrl(java.lang.String jdbcurl)
	{
		setJdbcUrl(getContext(), jdbcurl);
	}

	/**
	 * Set value of JdbcUrl
	 * @param context
	 * @param jdbcurl
	 */
	public final void setJdbcUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jdbcurl)
	{
		getMendixObject().setValue(context, MemberNames.JdbcUrl.toString(), jdbcurl);
	}

	/**
	 * @return value of AccountName
	 */
	public final java.lang.String getAccountName()
	{
		return getAccountName(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountName
	 */
	public final java.lang.String getAccountName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccountName.toString());
	}

	/**
	 * Set value of AccountName
	 * @param accountname
	 */
	public final void setAccountName(java.lang.String accountname)
	{
		setAccountName(getContext(), accountname);
	}

	/**
	 * Set value of AccountName
	 * @param context
	 * @param accountname
	 */
	public final void setAccountName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountname)
	{
		getMendixObject().setValue(context, MemberNames.AccountName.toString(), accountname);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Db
	 */
	public final java.lang.String getDb()
	{
		return getDb(getContext());
	}

	/**
	 * @param context
	 * @return value of Db
	 */
	public final java.lang.String getDb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Db.toString());
	}

	/**
	 * Set value of Db
	 * @param db
	 */
	public final void setDb(java.lang.String db)
	{
		setDb(getContext(), db);
	}

	/**
	 * Set value of Db
	 * @param context
	 * @param db
	 */
	public final void setDb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String db)
	{
		getMendixObject().setValue(context, MemberNames.Db.toString(), db);
	}

	/**
	 * @return value of Schema
	 */
	public final java.lang.String getSchema()
	{
		return getSchema(getContext());
	}

	/**
	 * @param context
	 * @return value of Schema
	 */
	public final java.lang.String getSchema(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Schema.toString());
	}

	/**
	 * Set value of Schema
	 * @param schema
	 */
	public final void setSchema(java.lang.String schema)
	{
		setSchema(getContext(), schema);
	}

	/**
	 * Set value of Schema
	 * @param context
	 * @param schema
	 */
	public final void setSchema(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String schema)
	{
		getMendixObject().setValue(context, MemberNames.Schema.toString(), schema);
	}

	/**
	 * @return value of Role
	 */
	public final java.lang.String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final java.lang.String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(java.lang.String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @return value of Warehouse
	 */
	public final java.lang.String getWarehouse()
	{
		return getWarehouse(getContext());
	}

	/**
	 * @param context
	 * @return value of Warehouse
	 */
	public final java.lang.String getWarehouse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Warehouse.toString());
	}

	/**
	 * Set value of Warehouse
	 * @param warehouse
	 */
	public final void setWarehouse(java.lang.String warehouse)
	{
		setWarehouse(getContext(), warehouse);
	}

	/**
	 * Set value of Warehouse
	 * @param context
	 * @param warehouse
	 */
	public final void setWarehouse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehouse)
	{
		getMendixObject().setValue(context, MemberNames.Warehouse.toString(), warehouse);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return connectionBuilderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final snowflakeconnector.proxies.ConnectionBuilder that = (snowflakeconnector.proxies.ConnectionBuilder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
