// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package snowflakeconnector.proxies;

public class DatabaseProfile
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject databaseProfileMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SnowflakeConnector.DatabaseProfile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Identifier("Identifier"),
		Database("Database"),
		Schema("Schema"),
		Warehouse("Warehouse"),
		DatabaseProfile_SnowflakeConfiguration("SnowflakeConnector.DatabaseProfile_SnowflakeConfiguration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DatabaseProfile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SnowflakeConnector.DatabaseProfile"));
	}

	protected DatabaseProfile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject databaseProfileMendixObject)
	{
		if (databaseProfileMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SnowflakeConnector.DatabaseProfile", databaseProfileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SnowflakeConnector.DatabaseProfile");

		this.databaseProfileMendixObject = databaseProfileMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DatabaseProfile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static snowflakeconnector.proxies.DatabaseProfile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return snowflakeconnector.proxies.DatabaseProfile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static snowflakeconnector.proxies.DatabaseProfile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new snowflakeconnector.proxies.DatabaseProfile(context, mendixObject);
	}

	public static snowflakeconnector.proxies.DatabaseProfile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return snowflakeconnector.proxies.DatabaseProfile.initialize(context, mendixObject);
	}

	public static java.util.List<snowflakeconnector.proxies.DatabaseProfile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<snowflakeconnector.proxies.DatabaseProfile> result = new java.util.ArrayList<snowflakeconnector.proxies.DatabaseProfile>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SnowflakeConnector.DatabaseProfile" + xpathConstraint))
			result.add(snowflakeconnector.proxies.DatabaseProfile.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Identifier
	 */
	public final java.lang.String getIdentifier()
	{
		return getIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of Identifier
	 */
	public final java.lang.String getIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Identifier.toString());
	}

	/**
	 * Set value of Identifier
	 * @param identifier
	 */
	public final void setIdentifier(java.lang.String identifier)
	{
		setIdentifier(getContext(), identifier);
	}

	/**
	 * Set value of Identifier
	 * @param context
	 * @param identifier
	 */
	public final void setIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identifier)
	{
		getMendixObject().setValue(context, MemberNames.Identifier.toString(), identifier);
	}

	/**
	 * @return value of Database
	 */
	public final java.lang.String getDatabase()
	{
		return getDatabase(getContext());
	}

	/**
	 * @param context
	 * @return value of Database
	 */
	public final java.lang.String getDatabase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Database.toString());
	}

	/**
	 * Set value of Database
	 * @param database
	 */
	public final void setDatabase(java.lang.String database)
	{
		setDatabase(getContext(), database);
	}

	/**
	 * Set value of Database
	 * @param context
	 * @param database
	 */
	public final void setDatabase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String database)
	{
		getMendixObject().setValue(context, MemberNames.Database.toString(), database);
	}

	/**
	 * @return value of Schema
	 */
	public final java.lang.String getSchema()
	{
		return getSchema(getContext());
	}

	/**
	 * @param context
	 * @return value of Schema
	 */
	public final java.lang.String getSchema(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Schema.toString());
	}

	/**
	 * Set value of Schema
	 * @param schema
	 */
	public final void setSchema(java.lang.String schema)
	{
		setSchema(getContext(), schema);
	}

	/**
	 * Set value of Schema
	 * @param context
	 * @param schema
	 */
	public final void setSchema(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String schema)
	{
		getMendixObject().setValue(context, MemberNames.Schema.toString(), schema);
	}

	/**
	 * @return value of Warehouse
	 */
	public final java.lang.String getWarehouse()
	{
		return getWarehouse(getContext());
	}

	/**
	 * @param context
	 * @return value of Warehouse
	 */
	public final java.lang.String getWarehouse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Warehouse.toString());
	}

	/**
	 * Set value of Warehouse
	 * @param warehouse
	 */
	public final void setWarehouse(java.lang.String warehouse)
	{
		setWarehouse(getContext(), warehouse);
	}

	/**
	 * Set value of Warehouse
	 * @param context
	 * @param warehouse
	 */
	public final void setWarehouse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehouse)
	{
		getMendixObject().setValue(context, MemberNames.Warehouse.toString(), warehouse);
	}

	/**
	 * @return value of DatabaseProfile_SnowflakeConfiguration
	 */
	public final snowflakeconnector.proxies.SnowflakeConfiguration getDatabaseProfile_SnowflakeConfiguration() throws com.mendix.core.CoreException
	{
		return getDatabaseProfile_SnowflakeConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of DatabaseProfile_SnowflakeConfiguration
	 */
	public final snowflakeconnector.proxies.SnowflakeConfiguration getDatabaseProfile_SnowflakeConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		snowflakeconnector.proxies.SnowflakeConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DatabaseProfile_SnowflakeConfiguration.toString());
		if (identifier != null)
			result = snowflakeconnector.proxies.SnowflakeConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DatabaseProfile_SnowflakeConfiguration
	 * @param databaseprofile_snowflakeconfiguration
	 */
	public final void setDatabaseProfile_SnowflakeConfiguration(snowflakeconnector.proxies.SnowflakeConfiguration databaseprofile_snowflakeconfiguration)
	{
		setDatabaseProfile_SnowflakeConfiguration(getContext(), databaseprofile_snowflakeconfiguration);
	}

	/**
	 * Set value of DatabaseProfile_SnowflakeConfiguration
	 * @param context
	 * @param databaseprofile_snowflakeconfiguration
	 */
	public final void setDatabaseProfile_SnowflakeConfiguration(com.mendix.systemwideinterfaces.core.IContext context, snowflakeconnector.proxies.SnowflakeConfiguration databaseprofile_snowflakeconfiguration)
	{
		if (databaseprofile_snowflakeconfiguration == null)
			getMendixObject().setValue(context, MemberNames.DatabaseProfile_SnowflakeConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DatabaseProfile_SnowflakeConfiguration.toString(), databaseprofile_snowflakeconfiguration.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return databaseProfileMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final snowflakeconnector.proxies.DatabaseProfile that = (snowflakeconnector.proxies.DatabaseProfile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SnowflakeConnector.DatabaseProfile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
