// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package snowflakeconnector.proxies;

public enum Enum_QueryStatus
{
	RUNNING(new java.lang.String[][] { new java.lang.String[] { "en_US", "Running" } }),
	ABORTING(new java.lang.String[][] { new java.lang.String[] { "en_US", "Aborting" } }),
	SUCCESS(new java.lang.String[][] { new java.lang.String[] { "en_US", "Success" } }),
	FAILED_WITH_ERROR(new java.lang.String[][] { new java.lang.String[] { "en_US", "Failed with Error" } }),
	QUEUED(new java.lang.String[][] { new java.lang.String[] { "en_US", "Queued" } }),
	DISCONNECTED(new java.lang.String[][] { new java.lang.String[] { "en_US", "Disconnected" } }),
	RESUMING_WAREHOUSE(new java.lang.String[][] { new java.lang.String[] { "en_US", "Resuming Warehouse" } }),
	BLOCKED(new java.lang.String[][] { new java.lang.String[] { "en_US", "Blocked" } }),
	NO_DATA(new java.lang.String[][] { new java.lang.String[] { "en_US", "No Data" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_QueryStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
