// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package snowflakeconnector.proxies;

public enum Enum_WarehouseSize
{
	X_Small(new java.lang.String[][] { new java.lang.String[] { "en_US", "X-Small" } }),
	Small(new java.lang.String[][] { new java.lang.String[] { "en_US", "Small" } }),
	Medium(new java.lang.String[][] { new java.lang.String[] { "en_US", "Medium" } }),
	Large(new java.lang.String[][] { new java.lang.String[] { "en_US", "Large" } }),
	X_Large(new java.lang.String[][] { new java.lang.String[] { "en_US", "X-Large" } }),
	_2X_Large(new java.lang.String[][] { new java.lang.String[] { "en_US", "2X-Large" } }),
	_3X_Large(new java.lang.String[][] { new java.lang.String[] { "en_US", "3X-Large" } }),
	_4X_Large(new java.lang.String[][] { new java.lang.String[] { "en_US", "4X-Large" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_WarehouseSize(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
