// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package snowflakeconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the SnowflakeConnector module
	public static snowflakeconnector.proxies.AsyncQueryResult asyncQuery_Execute(IContext context, java.lang.String _databaseProfileId, java.lang.String _sqlQuery)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			params.put("SqlQuery", _sqlQuery);
			IMendixObject result = (IMendixObject)Core.execute(context, "SnowflakeConnector.AsyncQuery_Execute", params);
			return result == null ? null : snowflakeconnector.proxies.AsyncQueryResult.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<snowflakeconnector.proxies.Result> asyncQuery_GetResult(IContext context, java.lang.String _databaseProfileId, java.lang.String _queryId)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			params.put("QueryId", _queryId);
			java.util.List<IMendixObject> objs = Core.execute(context, "SnowflakeConnector.AsyncQuery_GetResult", params);
			java.util.List<snowflakeconnector.proxies.Result> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<snowflakeconnector.proxies.Result>();
				for (IMendixObject obj : objs)
					result.add(snowflakeconnector.proxies.Result.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static snowflakeconnector.proxies.AsyncQueryStatus asyncQuery_GetStatus(IContext context, java.lang.String _databaseProfileId, java.lang.String _queryId)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			params.put("QueryId", _queryId);
			IMendixObject result = (IMendixObject)Core.execute(context, "SnowflakeConnector.AsyncQuery_GetStatus", params);
			return result == null ? null : snowflakeconnector.proxies.AsyncQueryStatus.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_AsyncQueryExample_Create(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_AsyncQueryExample_Create", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_AsyncQueryExample_GetResult(IContext context, snowflakeconnector.proxies.AsyncQueryExample _asyncQueryExample)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AsyncQueryExample", _asyncQueryExample == null ? null : _asyncQueryExample.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_AsyncQueryExample_GetResult", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_AsyncQueryExample_GetStatus(IContext context, snowflakeconnector.proxies.AsyncQueryExample _asyncQueryExample)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AsyncQueryExample", _asyncQueryExample == null ? null : _asyncQueryExample.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_AsyncQueryExample_GetStatus", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_AsyncQueryExample_ShowQuery(IContext context, snowflakeconnector.proxies.AsyncQueryExample _asyncQueryExample)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AsyncQueryExample", _asyncQueryExample == null ? null : _asyncQueryExample.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_AsyncQueryExample_ShowQuery", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_DatabaseProfile_JdbcConnectionTest(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_DatabaseProfile_JdbcConnectionTest", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_DatabaseProfile_Save(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_DatabaseProfile_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_SnowflakeConfiguration_ConnectivityTest(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_SnowflakeConfiguration_ConnectivityTest", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_SnowflakeConfiguration_Save(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_SnowflakeConfiguration_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_Warehouse_ApplyNewSize(IContext context, snowflakeconnector.proxies.WarehouseEdit _warehouseEdit, snowflakeconnector.proxies.DatabaseProfile _databaseProfile, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("WarehouseEdit", _warehouseEdit == null ? null : _warehouseEdit.getMendixObject());
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_Warehouse_ApplyNewSize", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_Warehouse_ChangeSize_Show(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_Warehouse_ChangeSize_Show", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_Warehouse_Overview_Show(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "SnowflakeConnector.AT_Warehouse_Overview_Show", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_Warehouse_Refresh(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_Warehouse_Refresh", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aT_Warehouse_Save(IContext context, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
			Core.execute(context, "SnowflakeConnector.AT_Warehouse_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static snowflakeconnector.proxies.ConnectionBuilder connectionBuilder_Create(IContext context, java.lang.String _databaseProfileId)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			IMendixObject result = (IMendixObject)Core.execute(context, "SnowflakeConnector.ConnectionBuilder_Create", params);
			return result == null ? null : snowflakeconnector.proxies.ConnectionBuilder.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static snowflakeconnector.proxies.Enum_WarehouseSize convertSizeStringToEnum(IContext context, java.lang.String _size)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Size", _size);
			java.lang.String result = (java.lang.String)Core.execute(context, "SnowflakeConnector.ConvertSizeStringToEnum", params);
			if (result == null)
				return null;
			return snowflakeconnector.proxies.Enum_WarehouseSize.valueOf(result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static snowflakeconnector.proxies.DatabaseProfile databaseProfile_Retrieve(IContext context, java.lang.String _databaseProfileId)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			IMendixObject result = (IMendixObject)Core.execute(context, "SnowflakeConnector.DatabaseProfile_Retrieve", params);
			return result == null ? null : snowflakeconnector.proxies.DatabaseProfile.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static snowflakeconnector.proxies.WarehouseEdit dS_WarehouseEdit_Create(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "SnowflakeConnector.DS_WarehouseEdit_Create", params);
			return result == null ? null : snowflakeconnector.proxies.WarehouseEdit.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<snowflakeconnector.proxies.WarehouseInfo> getWarehouseInfo(IContext context, java.lang.String _databaseProfileId, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "SnowflakeConnector.GetWarehouseInfo", params);
			java.util.List<snowflakeconnector.proxies.WarehouseInfo> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<snowflakeconnector.proxies.WarehouseInfo>();
				for (IMendixObject obj : objs)
					result.add(snowflakeconnector.proxies.WarehouseInfo.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String lognode_SnowflakeConnector(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.String)Core.execute(context, "SnowflakeConnector.Lognode_SnowflakeConnector", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<snowflakeconnector.proxies.Result> query_Execute(IContext context, java.lang.String _databaseProfileId, java.lang.String _sqlQuery)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			params.put("SqlQuery", _sqlQuery);
			java.util.List<IMendixObject> objs = Core.execute(context, "SnowflakeConnector.Query_Execute", params);
			java.util.List<snowflakeconnector.proxies.Result> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<snowflakeconnector.proxies.Result>();
				for (IMendixObject obj : objs)
					result.add(snowflakeconnector.proxies.Result.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static snowflakeconnector.proxies.ConnectionBuilder sF_ConnectionBuilder_SetValues(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration, snowflakeconnector.proxies.ConnectionBuilder _connectionBuilder)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			params.put("ConnectionBuilder", _connectionBuilder == null ? null : _connectionBuilder.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "SnowflakeConnector.SF_ConnectionBuilder_SetValues", params);
			return result == null ? null : snowflakeconnector.proxies.ConnectionBuilder.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sF_SnowflakeConfiguration_EncryptPassword(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			Core.execute(context, "SnowflakeConnector.SF_SnowflakeConfiguration_EncryptPassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<snowflakeconnector.proxies.Result> sF_SnowflakeConfiguration_ExecuteConnectivityTest(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "SnowflakeConnector.SF_SnowflakeConfiguration_ExecuteConnectivityTest", params);
			java.util.List<snowflakeconnector.proxies.Result> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<snowflakeconnector.proxies.Result>();
				for (IMendixObject obj : objs)
					result.add(snowflakeconnector.proxies.Result.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String sF_SnowflakeConfiguration_GetJdbcUrl(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
			return (java.lang.String)Core.execute(context, "SnowflakeConnector.SF_SnowflakeConfiguration_GetJdbcUrl", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String sF_SnowflakeConfiguration_GetPassword(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
			return (java.lang.String)Core.execute(context, "SnowflakeConnector.SF_SnowflakeConfiguration_GetPassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sF_Warehouse_AlterSize(IContext context, snowflakeconnector.proxies.Enum_WarehouseSize _newSize, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NewSize", _newSize == null ? null : _newSize.name());
			params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "SnowflakeConnector.SF_Warehouse_AlterSize", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sF_Warehouse_RefreshInfo(IContext context, snowflakeconnector.proxies.Warehouse _warehouse, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
			params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "SnowflakeConnector.SF_Warehouse_RefreshInfo", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Long statement_Execute(IContext context, java.lang.String _databaseProfileId, java.lang.String _sqlQuery)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DatabaseProfileId", _databaseProfileId);
			params.put("SqlQuery", _sqlQuery);
			return (java.lang.Long)Core.execute(context, "SnowflakeConnector.Statement_Execute", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}