// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package snowflakeconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the SnowflakeConnector module
	public static snowflakeconnector.proxies.AsyncQueryResult asyncQuery_Execute(IContext context, java.lang.String _databaseProfileId, java.lang.String _sqlQuery)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		params.put("SqlQuery", _sqlQuery);
		IMendixObject result = (IMendixObject)Core.microflowCall("SnowflakeConnector.AsyncQuery_Execute").withParams(params).execute(context);
		return result == null ? null : snowflakeconnector.proxies.AsyncQueryResult.initialize(context, result);
	}
	public static java.util.List<snowflakeconnector.proxies.Result> asyncQuery_GetResult(IContext context, java.lang.String _databaseProfileId, java.lang.String _queryId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		params.put("QueryId", _queryId);
		java.util.List<IMendixObject> objs = Core.microflowCall("SnowflakeConnector.AsyncQuery_GetResult").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> snowflakeconnector.proxies.Result.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static snowflakeconnector.proxies.AsyncQueryStatus asyncQuery_GetStatus(IContext context, java.lang.String _databaseProfileId, java.lang.String _queryId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		params.put("QueryId", _queryId);
		IMendixObject result = (IMendixObject)Core.microflowCall("SnowflakeConnector.AsyncQuery_GetStatus").withParams(params).execute(context);
		return result == null ? null : snowflakeconnector.proxies.AsyncQueryStatus.initialize(context, result);
	}
	public static void aT_AsyncQueryExample_Create(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_AsyncQueryExample_Create").withParams(params).execute(context);
	}
	public static void aT_AsyncQueryExample_GetResult(IContext context, snowflakeconnector.proxies.AsyncQueryExample _asyncQueryExample)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AsyncQueryExample", _asyncQueryExample == null ? null : _asyncQueryExample.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_AsyncQueryExample_GetResult").withParams(params).execute(context);
	}
	public static void aT_AsyncQueryExample_GetStatus(IContext context, snowflakeconnector.proxies.AsyncQueryExample _asyncQueryExample)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AsyncQueryExample", _asyncQueryExample == null ? null : _asyncQueryExample.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_AsyncQueryExample_GetStatus").withParams(params).execute(context);
	}
	public static void aT_AsyncQueryExample_ShowQuery(IContext context, snowflakeconnector.proxies.AsyncQueryExample _asyncQueryExample)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AsyncQueryExample", _asyncQueryExample == null ? null : _asyncQueryExample.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_AsyncQueryExample_ShowQuery").withParams(params).execute(context);
	}
	public static void aT_DatabaseProfile_JdbcConnectionTest(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_DatabaseProfile_JdbcConnectionTest").withParams(params).execute(context);
	}
	public static void aT_DatabaseProfile_Save(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_DatabaseProfile_Save").withParams(params).execute(context);
	}
	public static void aT_SnowflakeConfiguration_ConnectivityTest(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_SnowflakeConfiguration_ConnectivityTest").withParams(params).execute(context);
	}
	public static void aT_SnowflakeConfiguration_Save(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_SnowflakeConfiguration_Save").withParams(params).execute(context);
	}
	public static void aT_Warehouse_ChangeSize(IContext context, snowflakeconnector.proxies.WarehouseEdit _warehouseEdit, snowflakeconnector.proxies.DatabaseProfile _databaseProfile, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WarehouseEdit", _warehouseEdit == null ? null : _warehouseEdit.getMendixObject());
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_Warehouse_ChangeSize").withParams(params).execute(context);
	}
	public static void aT_Warehouse_ChangeSize_Show(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_Warehouse_ChangeSize_Show").withParams(params).execute(context);
	}
	public static void aT_Warehouse_Refresh(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_Warehouse_Refresh").withParams(params).execute(context);
	}
	public static void aT_Warehouse_Save(IContext context, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
		Core.microflowCall("SnowflakeConnector.AT_Warehouse_Save").withParams(params).execute(context);
	}
	public static snowflakeconnector.proxies.ConnectionBuilder connectionBuilder_Create(IContext context, java.lang.String _databaseProfileId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		IMendixObject result = (IMendixObject)Core.microflowCall("SnowflakeConnector.ConnectionBuilder_Create").withParams(params).execute(context);
		return result == null ? null : snowflakeconnector.proxies.ConnectionBuilder.initialize(context, result);
	}
	public static snowflakeconnector.proxies.ConnectionBuilder connectionBuilder_SetValues(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration, snowflakeconnector.proxies.ConnectionBuilder _connectionBuilder)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		params.put("ConnectionBuilder", _connectionBuilder == null ? null : _connectionBuilder.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("SnowflakeConnector.ConnectionBuilder_SetValues").withParams(params).execute(context);
		return result == null ? null : snowflakeconnector.proxies.ConnectionBuilder.initialize(context, result);
	}
	public static java.util.List<snowflakeconnector.proxies.Result> connectionTest_ParameterizedQuery_Execute(IContext context, java.lang.String _databaseProfileId, java.lang.String _attribute, java.lang.String _value)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		params.put("Attribute", _attribute);
		params.put("Value", _value);
		java.util.List<IMendixObject> objs = Core.microflowCall("SnowflakeConnector.ConnectionTest_ParameterizedQuery_Execute").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> snowflakeconnector.proxies.Result.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static snowflakeconnector.proxies.Enum_WarehouseSize convertSizeStringToEnum(IContext context, java.lang.String _size)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Size", _size);
		java.lang.String result = (java.lang.String) Core.microflowCall("SnowflakeConnector.ConvertSizeStringToEnum").withParams(params).execute(context);
		return result == null ? null : snowflakeconnector.proxies.Enum_WarehouseSize.valueOf(result);
	}
	public static java.lang.String lognode_SnowflakeConnector(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("SnowflakeConnector.Lognode_SnowflakeConnector").withParams(params).execute(context);
	}
	public static void snowflakeConfiguration_EncryptPassword(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		Core.microflowCall("SnowflakeConnector.SnowflakeConfiguration_EncryptPassword").withParams(params).execute(context);
	}
	public static java.util.List<snowflakeconnector.proxies.Result> snowflakeConfiguration_ExecuteConnectivityTest(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("SnowflakeConnector.SnowflakeConfiguration_ExecuteConnectivityTest").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> snowflakeconnector.proxies.Result.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.lang.String snowflakeConfiguration_GetJdbcUrl(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
		return (java.lang.String) Core.microflowCall("SnowflakeConnector.SnowflakeConfiguration_GetJdbcUrl").withParams(params).execute(context);
	}
	public static java.lang.String snowflakeConfiguration_GetPassword(IContext context, snowflakeconnector.proxies.SnowflakeConfiguration _snowflakeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SnowflakeConfiguration", _snowflakeConfiguration == null ? null : _snowflakeConfiguration.getMendixObject());
		return (java.lang.String) Core.microflowCall("SnowflakeConnector.SnowflakeConfiguration_GetPassword").withParams(params).execute(context);
	}
	public static java.lang.Long statement_Execute(IContext context, java.lang.String _databaseProfileId, java.lang.String _sqlStatement)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		params.put("SqlStatement", _sqlStatement);
		return (java.lang.Long) Core.microflowCall("SnowflakeConnector.Statement_Execute").withParams(params).execute(context);
	}
	public static boolean vAL_DatabaseProfile(IContext context, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("SnowflakeConnector.VAL_DatabaseProfile").withParams(params).execute(context);
	}
	public static boolean warehouse_AlterSize(IContext context, snowflakeconnector.proxies.Enum_WarehouseSize _newSize, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewSize", _newSize == null ? null : _newSize.name());
		params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("SnowflakeConnector.Warehouse_AlterSize").withParams(params).execute(context);
	}
	public static java.util.List<snowflakeconnector.proxies.WarehouseInfo> warehouse_GetWarehouseInfo(IContext context, java.lang.String _databaseProfileId, snowflakeconnector.proxies.Warehouse _warehouse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseProfileId", _databaseProfileId);
		params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("SnowflakeConnector.Warehouse_GetWarehouseInfo").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> snowflakeconnector.proxies.WarehouseInfo.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static boolean warehouse_RefreshInfo(IContext context, snowflakeconnector.proxies.Warehouse _warehouse, snowflakeconnector.proxies.DatabaseProfile _databaseProfile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Warehouse", _warehouse == null ? null : _warehouse.getMendixObject());
		params.put("DatabaseProfile", _databaseProfile == null ? null : _databaseProfile.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("SnowflakeConnector.Warehouse_RefreshInfo").withParams(params).execute(context);
	}
	public static snowflakeconnector.proxies.WarehouseEdit warehouseEdit_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("SnowflakeConnector.WarehouseEdit_Create").withParams(params).execute(context);
		return result == null ? null : snowflakeconnector.proxies.WarehouseEdit.initialize(context, result);
	}
}
